### ISSUE TITLE
'module' object has no attribute 'qt4reactor'

### ISSUE THREAD

**Issue by Krystofsky** [geodrinx/gearthview#4]
What to do please.

I got Zope and Twisted module already and I did restart the program also. This message still show!!!??

**Comment by jesse-a-reilly** [comment]
I'm getting the same error, after installing Zope and Twisted:

> Couldn't load plugin gearthview due to an error when calling its classFactory() method
> Traceback (most recent call last):
> File "C:/PROGRA~1/QGISWI~1/apps/qgis/./python\qgis\utils.py", line 219, in startPlugin plugins[packageName] = package.classFactory(iface)
>  File "C:/Users/reillyj/.qgis2/python/plugins\gearthview__init__.py", line 52, in classFactory from gearthview import gearthview
>  File "C:/PROGRA~1/QGISWI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import mod = _builtin_import(name, globals, locals, fromlist, level)
> File "C:/Users/reillyj/.qgis2/python/plugins\gearthview\gearthview.py", line 68, in import qtreactor.qt4reactor as qt4reactor
> AttributeError: 'module' object has no attribute 'qt4reactor'

**Comment by ces3001** [comment]
I have this issue on macOS Sierra, fresh install. Error message upon install:
This plugin is broken. Python said: 'module' object has no attribute 'qt4reactor


QGIS version
2.18.0
QGIS code branch
Release 2.18
Compiled against Qt
4.8.6
Running against Qt
4.8.6
Compiled against GDAL/OGR
2.1.2
Running against GDAL/OGR
2.1.2
Compiled against GEOS
3.5.1-CAPI-1.9.1
Running against GEOS
3.5.1-CAPI-1.9.1 r4246
PostgreSQL Client Version
9.4.9
SpatiaLite Version
4.3.0a
QWT Version
6.1.3
PROJ.4 Version
492
QScintilla2 Version
2.9.3

Couldn't load plugin gearthview due to an error when calling its classFactory() method 

AttributeError: 'module' object has no attribute 'qt4reactor' 
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/ces/.qgis2/python/plugins/gearthview/__init__.py", line 58, in classFactory
    from gearthview import gearthview
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/ces/.qgis2/python/plugins/gearthview/gearthview.py", line 71, in 
    import qtreactor.qt4reactor as qt4reactor
AttributeError: 'module' object has no attribute 'qt4reactor'


Python version: 2.7.10 (default, Jul 30 2016, 18:31:42) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] 
QGIS version: 2.18.0 Las Palmas, exported 

Python Path:
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/ces/.qgis2/python
/Users/ces/.qgis2/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/C/Python/2.7
/Library/Frameworks/GEOS.framework/Versions/3/Python/2.7/site-packages
/Library/Python/2.7/site-packages/numpy-override
/Library/Python/2.7/site-packages/matplotlib-override
/Library/Frameworks/GDAL.framework/Versions/2.1/Python/2.7/site-packages
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
/Library/Python/2.7/site-packages
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC
/Users/ces/.qgis2//python
/Users/ces/.qgis2/python/plugins/gearthview/ext-libs

**Comment by todaz** [comment]
Hello,
so how to fix this error?
We got same.

**Comment by geodrinx** [comment]
what is your operating system ?

**Comment by geodrinx** [comment]
and what version of QGIS are you using ?
