### ISSUE TITLE
Couldn't load plugin gearthview-master due to an error when calling its classFactory() method

### ISSUE THREAD

**Issue by bscct** [geodrinx/gearthview#9]
Hello geodrinx,

Thank you for gearthview.  I used it in the past and it is great.  Thank you for updating it to work in newer versions of QGIS without having to find other components that were difficult or impossible to find.

Trying to install and use it with QGIS ver. 2.8.5-Wien  I get the Python error below upon trying to activate it.  

(As an FYI, when I first tried to install gearthview in my current version of QGIS I received an incorrect syntax error.  Looking for an answer I found that the problem was the hyphen in the name of the file, gearthview-master (found a comment that Python does not like hyphens hence the syntax error).  I changed the hyphen to an underscore and that error resolved.  However, I then learned I had gearthview installed in the wrong directory (in the directory for core plugins rather than for third party plugins).  After installing in the correct directory and getting the error below, I renamed the file to replace the underscore back to a hyphen to see if that might help.  For some reason I now do not get the syntax error, but instead I continue to get the error below.)

If it matters, my operating system is Windows 8.1, ver. 6.3.  Thank you again for gearthview, and I hope this is a simple fix.  Here is the error in the QGIS Plugin Manager Python error dialog:

**Couldn't load plugin gearthview-master due to an error when calling its classFactory() method**

Traceback (most recent call last):
  File "C:/PROGRA~1/QGISWI~1.5/apps/qgis-ltr/./python\qgis\utils.py", line 219, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/username/.qgis2/python/plugins\gearthview-master__init__.py", line 58, in classFactory
    from gearthview import gearthview
  File "C:/PROGRA~1/QGISWI~1.5/apps/qgis-ltr/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/username/.qgis2/python/plugins\gearthview-master\gearthview.py", line 71, in 
    import qtreactor.qt4reactor as qt4reactor
**AttributeError: 'module' object has no attribute 'qt4reactor'**

Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

QGIS version:
2.8.5-Wien Wien, 2b32796

Python path: ['C:/Users/username/.qgis2/python/plugins\processing', 'C:/PROGRA~1/QGISWI~1.5/apps/qgis-ltr/./python', u'C:/Users/username/.qgis2/python', u'C:/Users/username/.qgis2/python/plugins', 'C:/PROGRA~1/QGISWI~1.5/apps/qgis-ltr/./python/plugins', 'C:\PROGRA~1\QGISWI~1.5\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\PROGRA~1\QGISWI~1.5\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg', 'C:\PROGRA~1\QGISWI~1.5\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\PROGRA~1\QGISWI~1.5\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\PROGRA~1\QGISWI~1.5\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg', 'C:\PROGRA~1\QGISWI~1.5\bin\python27.zip', 'C:\PROGRA~1\QGISWI~1.5\apps\Python27\DLLs', 'C:\PROGRA~1\QGISWI~1.5\apps\Python27\lib', 'C:\PROGRA~1\QGISWI~1.5\apps\Python27\lib\plat-win', 'C:\PROGRA~1\QGISWI~1.5\apps\Python27\lib\lib-tk', 'C:\PROGRA~1\QGISWI~1.5\bin', 'C:\PROGRA~1\QGISWI~1.5\apps\Python27', 'C:\PROGRA~1\QGISWI~1.5\apps\Python27\lib\site-packages', 'C:\PROGRA~1\QGISWI~1.5\apps\Python27\lib\site-packages\PIL', 'C:\PROGRA~1\QGISWI~1.5\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg', 'C:\PROGRA~1\QGISWI~1.5\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\PROGRA~1\QGISWI~1.5\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg', 'C:\PROGRA~1\QGISWI~1.5\apps\Python27\lib\site-packages\win32', 'C:\PROGRA~1\QGISWI~1.5\apps\Python27\lib\site-packages\win32\lib', 'C:\PROGRA~1\QGISWI~1.5\apps\Python27\lib\site-packages\Pythonwin', 'C:\PROGRA~1\QGISWI~1.5\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\PROGRA~1\QGISWI~1.5\apps\Python27\lib\site-packages\six-1.3.0-py2.7.egg', 'C:\PROGRA~1\QGISWI~1.5\apps\Python27\lib\site-packages\wx-2.8-msw-unicode', 'C:\PROGRA~1\QGISWI~1.5\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg', 'C:\PROGRA~1\QGISWI~1.5\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg', u'C:/Users/username/.qgis2//python', 'C:\Users\username\.qgis2\python\plugins\gearthview-master\ext-libs', 'C:\Users\username\.qgis2\python\plugins\mmqgis/forms', 'C:\PROGRA~1\QGISWI~1.5\apps\qgis-ltr\python\plugins\fTools\tools']

**Comment by geodrinx** [comment]
Thank you for your accurate report. 

GEarthView needs to be installed into  .qgis2/python/plugins/   folder. 
If different from this, it returns error. 
Anyway I will indagate how to solve also the case. 

Thank you

Roberto

**Comment by ces3001** [comment]
I have this issue on macOS Sierra, fresh install.  Error message upon install:
This plugin is broken. Python said: 'module' object has no attribute 'qt4reactor'


QGIS version
2.18.0
QGIS code branch
Release 2.18
Compiled against Qt
4.8.6
Running against Qt
4.8.6
Compiled against GDAL/OGR
2.1.2
Running against GDAL/OGR
2.1.2
Compiled against GEOS
3.5.1-CAPI-1.9.1
Running against GEOS
3.5.1-CAPI-1.9.1 r4246
PostgreSQL Client Version
9.4.9
SpatiaLite Version
4.3.0a
QWT Version
6.1.3
PROJ.4 Version
492
QScintilla2 Version 
2.9.3

Couldn't load plugin gearthview due to an error when calling its classFactory() method 

AttributeError: 'module' object has no attribute 'qt4reactor' 
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/ces/.qgis2/python/plugins/gearthview/__init__.py", line 58, in classFactory
    from gearthview import gearthview
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/ces/.qgis2/python/plugins/gearthview/gearthview.py", line 71, in 
    import qtreactor.qt4reactor as qt4reactor
AttributeError: 'module' object has no attribute 'qt4reactor'


Python version: 2.7.10 (default, Jul 30 2016, 18:31:42) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] 
QGIS version: 2.18.0 Las Palmas, exported 

Python Path:
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/ces/.qgis2/python
/Users/ces/.qgis2/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/C/Python/2.7
/Library/Frameworks/GEOS.framework/Versions/3/Python/2.7/site-packages
/Library/Python/2.7/site-packages/numpy-override
/Library/Python/2.7/site-packages/matplotlib-override
/Library/Frameworks/GDAL.framework/Versions/2.1/Python/2.7/site-packages
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
/Library/Python/2.7/site-packages
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC
/Users/ces/.qgis2//python
/Users/ces/.qgis2/python/plugins/gearthview/ext-libs
